server:
  port: 8080
management:
  endpoint:
    shutdown:
      enabled: true
      sensitive: false
  endpoints:
    web:
      exposure:
        include: "shutdown"
spring:
  security:
    user:
      name: admin
      password: xxxxx

  redis:
    host: localhost
    port: 6379
    database: 1
    password:
  # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.139.com
    username: xx@139.com
    password: xxxxxxx
    test-connection: false
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactor
jusic:
  music-expire-time: 1200000
  retry-count: 1
  vote-rate: 0.3
  default-music-file: 'file:/usr/local/nginx/html/default-list.txt' # ## #'classpath:music/default-list.txt'
  wy-top-url: '3778678'
  music-json: 'file:/usr/local/nginx/html/lizhimusic.json'#'classpath:lizhimusic.json'#json格式歌曲列表（for禁歌） # #
  music-serve-domain: 'http://xxxxxx:1234'
  music-serve-domain-qq: 'http://xxxxx:4567'
  music-serve-domain-mg: 'http://xxxxx:5678'#'http://localhost:5678'#
  music-serve-domain-kw-xm: 'http://www.alang.run:9012'#'http://localhost:9012'#
  mail-send-from: 'xx@139.com'
  mail-send-to: 'xxx@qq.com'
  serverJUrl: 'https://sc.ftqq.com/xxxxxxx.send'
  ip_house: 3
  house_size: 32


